### ISSUE TITLE
Please delete a commit 

### ISSUE THREAD

**Issue by yliu-atwork** [SamGurr/RClub_practice#1]
Hey Sam, I didn't realize I was in your repo when I committed [this](https://github.com/SamGurr/RClub/commit/7f15752ee4106ac8eebe7ae0a0fd8d453d9374c6). It is nonsense.
Could you delete it? 

Could I have deleted it on my end?

**Comment by SamGurr** [comment]
done - seems like the .DS_store file was added possibly as a result of the directory for the cloned repo on your desktop - I deleted it using 'rm' call before git add, commit, and push. These commands are in the tutorial, feel free to give it a try if another file comes up that you'd like to delete and push to the repo
